### ISSUE TITLE
Incorrect template expansion

### ISSUE THREAD

**Issue by cifkao** [attardi/wikiextractor#10]
The article `Abraham Lincoln` (307) contains the following:
```
* {{NYTtopic|people/l/abraham_lincoln}}
```
When using the `--sections` option, this is expanded to:
```
<li> [http://topics.nytimes.com/top/reference/timestopics/people/l/abraham_lincoln /index.html {{safesubst:#Invoke:String|replace|{{{{ </li>
```

The article `Arabic Languages` (803) contains a lot of templates at the beginning. These are expanded as:
```
{{#switch:
 {{#if: 
 | {{lc: }} 
 | main
 | other
```

I checked that the log contains no errors or warnings for these two articles.

**Comment by attardi** [comment]
Fixed in version 2.22.
