### ISSUE TITLE
IndexError: string index out of range when collecting templates

### ISSUE THREAD

**Issue by desile** [attardi/wikiextractor#106]
Command:

> wikiextractor-master/WikiExtractor.py -o out2 --templates template ruwiki-latest-pages-articles.xml

Log:

> INFO: Preprocessing 'ruwiki-latest-pages-articles.xml' to collect template definitions: this may take some time.
> INFO: Preprocessed 100000 pages
> INFO: Preprocessed 200000 pages
> Traceback (most recent call last):
>   File "wikiextractor-master/WikiExtractor.py", line 3143, in <module>
>     main()
>   File "wikiextractor-master/WikiExtractor.py", line 3139, in main
>     args.compress, args.processes)
>   File "wikiextractor-master/WikiExtractor.py", line 2802, in process_dump
>     load_templates(input, template_file)
>   File "wikiextractor-master/WikiExtractor.py", line 2659, in load_templates
>     define_template(title, text)
>   File "wikiextractor-master/WikiExtractor.py", line 1883, in define_template
>     m = re.match('#REDIRECT.*?\[\[([^\]]*)]]', page[0], re.IGNORECASE)
> IndexError: string index out of range

**Comment by Player701** [comment]
Having the same issue. Used this dump: http://dumps.wikimedia.your.org/ruwiki/20170201/ruwiki-20170201-pages-articles.xml.bz2

**Comment by attardi** [comment]
I confirm the problem.
Strangely enough, if I repeat the command, after having extracted te templates, it seems to work fine.
Could you try?

**Comment by attardi** [comment]
Fixed. Download the latest version, remove the old template file and try again.

**Comment by Player701** [comment]
Now the templates are parsed without erroring out, but during article extraction I see messages like this:

> WARNING:root:Template errors in article 'Слоновые' (10): title(2) recursion(0, 0, 0)
> WARNING:root:Template errors in article 'Россия' (9): title(0) recursion(227660, 0, 0)
> WARNING:root:Template errors in article 'Российская империя' (29): title(0) recursion(455320, 0, 0)
> WARNING:root:Template errors in article 'Гражданская война в России' (35): title(0) recursion(227660, 0, 0)
> WARNING:root:Template errors in article 'Содружество Независимых Государств' (39): title(0) recursion(227660, 0, 0)

It makes the extraction proceed very slowly, most likely because the script tries to expand a certain template recursively (guessing by the above warning messages) a very large number of times before finally giving up.

The dump file is the same (link in the original post). Please try to find out what might be wrong, if possible. Thank you very much.
