### ISSUE TITLE
Filtering by ID

### ISSUE THREAD

**Issue by rafspiny** [attardi/wikiextractor#109]
I found myself wondering if I could use WikiExtractor to extract text from the xml dump only for certain IDs.
I extracted a list of pages IDs of interest using [this tool](https://petscan.wmflabs.org/).

I was wondering if this feature can be useful to someone else as well.
In such a case, I have the relative changes in my [forked version](https://github.com/attardi/wikiextractor/compare/master...rafspiny:master).

Of course, feel free to ignore this and close the issue if this feature request is not of (broad) interest.
Thank you for all your works.

**Comment by attardi** [comment]
I would not complicate the script itself.
You might want instead to extend the script extractPage.py that does a similar job of selecting articles from the dump.
