### ISSUE TITLE
Error while preprocessing templates: WikiExtractor.py:1904

### ISSUE THREAD

**Issue by nkruglikov** [attardi/wikiextractor#114]
Hello, 

I'm trying to process the Russian Wikipedia dump. The tool works for a while, then crashes after processing about 200000 pages.

Here's how I launch it:
```
$ ./WikiExtractor.py -o ../data/wikiextractor_results/ -c --json -ns 0 --filter_disambig_pages --templates ../data/wikiextractor_results/templates ../data/ruwiki-latest-pages-articles.xml.bz2
```

Here's the output:
```
INFO: Preprocessing '../data/ruwiki-latest-pages-articles.xml.bz2' to collect template definitions: this may take some time.
INFO: Preprocessed 100000 pages
INFO: Preprocessed 200000 pages
Traceback (most recent call last):
  File "./WikiExtractor.py", line 3165, in <module>
    main()
  File "./WikiExtractor.py", line 3155, in main
    args.compress, args.processes)
  File "./WikiExtractor.py", line 2818, in process_dump
    load_templates(input, template_file)
  File "./WikiExtractor.py", line 2679, in load_templates
    define_template(title, text)
  File "./WikiExtractor.py", line 1904, in define_template
    m = re.match('#REDIRECT.*?\[\[([^\]]*)]]', page[0], re.IGNORECASE)
IndexError: string index out of range
```

**Comment by attardi** [comment]
This has happen before with Russian. Try running it again using the extracted templates.

**Comment by nkruglikov** [comment]
Thank you for the quick response. It works, but obviously it doesn't process the rest of the dump in search for templates.

The script has loaded around 7000 templates. It looks close to the total number of templates in Russian Wikipedia, but I am not sure that all templates are stored at the beginning of the dump.

**Comment by attardi** [comment]
There was a problem with empty templates.
Please download the newest version and try again.

**Comment by nkruglikov** [comment]
That fixed it!
However, I must admit that now processing slowed down very significantly. One in three articles is processing for about a *minute*, resulting in something like that:

```
WARNING: Template errors in article 'Красная книга' (15): title(0) recursion(237568, 0, 0)
```

**Comment by attardi** [comment]
The problem stems from the expansion of template {{NAMESPACE}}
which is defined as:

    {{Soft redirect|mw:Help:Magic words/ru#Пространство имён}}

which in turn is defined as:

    {{#if:{{NAMESPACE}}|[[Файл:Redirectltr.png|link=|#перенаправление]]<span class="redirectText" id="softredirect">'''{{#if:{{{url|}}}|[{{{url}}}]|[[:{{{1}}}|{{{2|{{{1}}}}}}]]}}'''</span><br /><span style="font-size:85%; padding-left:52px;">Эта страница — [[m:Мягкое перенаправление|мягкое перенаправление]]</span>|{{db-nocontent|Мягкие перенаправления в основном пространстве не приняты}}}}{{#ifeq:{{NAMESPACENUMBER}}|10|{{#if:{{{nocat|}}}||[[Категория:Шаблоны:Мягкие перенаправления]]}}}}                                                                    

whose expansion requires expanding {{NAMESPACE}} again.
