### ISSUE TITLE
AttributeError when using the namespaces option

### ISSUE THREAD

**Issue by Kameegaming** [attardi/wikiextractor#16]
File "wikiextractor-master/WikiExtractor.py", line 2453, in
main()
File "wikiextractor-master/WikiExtractor.py", line 2409, in main
acceptedNamespaces = set(args.ns.split(','))
AttributeError: 'Namespace' object has no attribute 'ns'

happens regardless of using -ns or --namespaces

fixed by acceptedNamespaces = set(args.namespaces.split(','))

**Comment by attardi** [comment]
Fixed, thank you.
