### ISSUE TITLE
[HELP REQUIRED] Using Templates

### ISSUE THREAD

**Issue by justachetan** [attardi/wikiextractor#184]
I am working with the Wikivoyage dump https://dumps.wikimedia.org/enwikivoyage/latest/

My problem is that there are templates for defining listings in Wiki Voyage. For instance, there is a template for See listing as shown here: https://en.wikivoyage.org/wiki/Template:See

What are the steps through which I can use this template to convert its usage in my XML dump to normal text?

**What I have tried**

- I copied the the following content into a file `see.temp`:
```
{{see
 | name    = | alt = | url = | email = 
 | address = | lat = | long = | directions = 
 | phone   = | tollfree = | fax = 
 | hours   = | price = 
 | wikipedia =
 | wikidata =
 | image =
 | lastedit =
 | content = 
}}
```

- I passed `see.temp` as the value for the option `--templates` while running WikiExtractor.py

The part where the listing object is in the XML was promptly omitted in the extracted text. 

Any help with this would be appreciated.

**Comment by chaojiang06** [comment]
Hi,

It seems a lot of people have problems with the template expansion function, I found an old version at http://medialab.di.unipi.it/wiki/Wikipedia_Extractor. It works well.

You need to use python2 to run it.

Thanks!

**Comment by justachetan** [comment]
Oh, nvm, I ended up writing my own regex expressions to resolve this. Still, thanks for the tip 😄 !
