### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by mykinator** [attardi/wikiextractor#19]
python WikiExtractor.py 
File "WikiExtractor.py", line 877
afterPat = { o:re.compile(openPat+'|'+c, re.DOTALL) for o,c in izip(openDelim, closeDelim)}
^
SyntaxError: invalid syntax

====
Any idea what I am doing wrong here? I am using python 2.6.1

**Comment by Kameegaming** [comment]
can you post the surrounding lines from the code?

**Comment by mykinator** [comment]
Turns out I needed python 2.7. Something to do with needing a dictionary comprehension.
