### ISSUE TITLE
Output json format file

### ISSUE THREAD

**Issue by Lepiloff** [attardi/wikiextractor#191]
Hi!
I run command 
`python WikiExtractor.py --json enwiki-latest-pages-articles.xml.bz2`
and expected get one json file as output, but got
```
INFO: Finished 7-process extraction of 5940667 articles in 9328.5s (636.8 art/s)
INFO: total of page: 10433470, total of articl page: 5940667; total of used articl page: 5940667
```
and folder **text** with many inner folders like **AA**, **AB**, **AC** ...  
What command should I use to get one json file?I want to use it as described in this manual https://github.com/NVIDIA/Megatron-LM#collecting-wikipedia-training-data

**Comment by HjalmarrSv** [comment]
In linux you can postprocess with cat, e.g. cat --squeeze-blank wiki/*/* > wiki/wiki.txt

This will produce one large file of all the small files. This file is made up of articles, with the json tags on each article.

You could also change the code of wikiextractor, from 1M to something larger. This will produce larger files, or even a large file if filesize is large enough, computer resources permitting.
