### ISSUE TITLE
cgi.escape was removed in Python 3.8

### ISSUE THREAD

**Issue by tirkarthi** [attardi/wikiextractor#198]
`cgi.escape` was deprecated and removed in Python 3.8 . Using `html.escape` is recommended. Thanks.

https://github.com/attardi/wikiextractor/blob/3162bb6c3c9ebd2d15be507aa11d6fa818a454ac/WikiExtractor.py#L811

**Comment by HjalmarrSv** [comment]
There is a fork that has a fix: Replace cgi.escape with html.escape due to deprecation warning 
infolab-csail/wikiextractor
michaelsilver committed 9 days ago

**Comment by attardi** [comment]
Fixed. Thank you.
