### ISSUE TITLE
How to use extractPage.py

### ISSUE THREAD

**Issue by agoyaliitk** [attardi/wikiextractor#20]
I have a list of wikipedia urls in a text file and I want the text (from wikipedia) of these articles only and not the whole wiki dump.
How can I use the extractor to do so?

**Comment by attardi** [comment]
You can use extractPage.py to get individual articles from an Wikipedia xml dump:
    extractPage.py wikidump-file --id ID > article.file
You need to know the ID of the page though.
Once you have the article on disk, you can apply wikipediaExtractor.py -a article-file
to extract the text.
Notice though that if the page uses templates, you will also need to supply the file with templates, which you can get with:

     WikiExtractor.py wikidumpfile --templates template-file

**Comment by agoyaliitk** [comment]
I need thousands of articles. So its not feasible to get individual articles one by one and take care which require template file and which do not

**Comment by attardi** [comment]
It should be fairly easy to modify extractPage.py to read a list from a file and extract those from the dump.

**Comment by Munzey** [comment]
you could use MWDumper to do something like this:
`bzcat enwiki-20080312-pages-articles.xml.bz2 | java -server -jar mwdumper.jar --format=xml --filter=exactlist:top.txt --filter=latest --filter=notalk > pages.xml`

where top.txt is a list of articles you want. However modifying extractPage.py could be a better route, considering the overhead of MWDumper using a mysql db.
