### ISSUE TITLE
WikiExtractor produces an empty output file

### ISSUE THREAD

**Issue by AsmaTidafi** [attardi/wikiextractor#207]
So I'm using the Wikipedia dump, I first split the `.xml` file into many `.xml` files where each file represents an article and surrounded by `<page> ... </page>`.
Now I want to parse those files to get the articles in plain text or in `.json` format so I'm using wikiExtractor, but it is producing empty files because the files contain only the "page" tag.

**Comment by SantoshGuptaML** [comment]
What was the solution?
