### ISSUE TITLE
License file

### ISSUE THREAD

**Issue by pashalot** [attardi/wikiextractor#210]
Hi!
I'd like to use this project, but there is no any license information. According to GitHub licensing policy this means that there is `no permission from the creators of the software to use, modify, or share the software`.
So if this project is intended as an open source it would be great to have a license file.
Thanks!
(more information about licensing can be found here https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository#choosing-the-right-license)

**Comment by hugovk** [comment]
A licence was added in https://github.com/attardi/wikiextractor/commit/f8282ab41090f94b7dfd17ce58a985f537db6c21

* https://github.com/attardi/wikiextractor/blob/master/LICENSE

**Comment by pashalot** [comment]
Great! Thank you so much!
