### ISSUE TITLE
WikiExtract.py does not exist

### ISSUE THREAD

**Issue by gsidorov** [attardi/wikiextractor#217]
I could not find the WikiExtract.py file within the extract folder, I think it should be included

Managed to solve the issue by downloading the package with pip install and then run it from there

Thanks for the amazing script

**Comment by bmichele** [comment]
@gsidorov You cannot find the file `WikiExtract.py` because it is not in the repo. The wikiextractor package you install with `pip install wikiextractor` is taken from here:
https://github.com/MouhamadAboShokor/wikiextractor/blob/master/wikiextractor/WikiExtractor.py

Hope it helps!

**Comment by gsidorov** [comment]
Yeah it does, thanks!
