### ISSUE TITLE
I keep getting error TypeError: %c requires int or char

### ISSUE THREAD

**Issue by alexvaca0** [attardi/wikiextractor#223]
Hi, both with your cirrus-extract.py and WikiExtractor.py I'm finding the following problem: 
TypeError: %c requires int or char
In the first case the error comes out at seconds after execution, while in the second case it preprocessess all texts, and when templates are created it crashes... Any solutions?

**Comment by Kai760** [comment]
you can fix like below (from line 140).
 
  ```
def _dirname(self):
        char1 = self.dir_index % 26
        char2 = int(self.dir_index / 26) % 26
        return os.path.join(self.path_name, '%c%c' % (ord('A') + char2, ord('A') + char1))
```

**Comment by attardi** [comment]
Fixed, thank you.
