### ISSUE TITLE
extract.py

### ISSUE THREAD

**Issue by kokoatom8akak** [attardi/wikiextractor#226]
Hi, I have a problem with extract.py.
Error code is this:
 File "/Users/wikiextractor/wikiextractor/extract.py", line 66, in get_url
    return "%s?curid=%s" % (options.urlbase, uid)
NameError: name 'options' is not defined

I don't know this is why, please help me!!!!!!

**Comment by memray** [comment]
There're a lot of bugs in this version but not super hard to fix. You can try this [one](https://github.com/zaemyung/wikiextractor) out or some other repos in pull request. Hope it helps.

**Comment by KyGao** [comment]
> There're a lot of bugs in this version but not super hard to fix. You can try this [one](https://github.com/zaemyung/wikiextractor) out or some other repos in pull request. Hope it helps.

You safe my life. Seems that facebookresearch/XLM didn't catch up with the modification by Wikiextractor

**Comment by kokoatom8akak** [comment]
@memray 
I can resolve my problems with your solution.
Thank you!

**Comment by attardi** [comment]
The current version has fixed this.
