### ISSUE TITLE
Missing arguments

### ISSUE THREAD

**Issue by geblanco** [attardi/wikiextractor#227]
Hi there!

I've tried to use the extractor, but many arguments are missing. They are present in the README, but the script complains about unrecognized arguments. Inspecting the code further I was unable to find such options.

Some of this missing arguments:
```bash
[--min_text_length MIN_TEXT_LENGTH]
[--filter_disambig_pages] [-it abbr,b,big]
[--log_file]
```

Maybe those were effectively removed or lost in previous commits?

Best,

**Comment by HjalmarrSv** [comment]
Check out the forks. Functionality varies depending on the interests of the maintainer.

**Comment by geblanco** [comment]
Yes, thank you :+1: 

I picked up from a specific [commit](https://github.com/attardi/wikiextractor/tree/e4abb4cbd019b0257824ee47c23dd163919b731b) and it is working,

Closing,
Best,
Guillermo

**Comment by Xalsar** [comment]
Thanks @geblanco , it worked perfectly!

It is a pity that they removed such useful functionalities in the most recent versions.

Does someone know if they are gonna add them back in a near future.
