### ISSUE TITLE
WikiExtractor.py: error: unrecognized arguments: --json

### ISSUE THREAD

**Issue by jp-ishimwe** [attardi/wikiextractor#236]
Hello dear maintainers,

After running this code:
`python -m wikiextractor.WikiExtractor -o kinyarwanda --json rwwiki-20201001-pages-articles-multistream.xml.bz2`

I have this issue:
`WikiExtractor.py: error: unrecognized arguments: --json
`
I am using python3 in ubuntu.

**Comment by attardi** [comment]
The --json option has been removed.
You can use the cirrus dumps that are already in json format:
	https://dumps.wikimedia.org/other/cirrussearch/current/

**Comment by jp-ishimwe** [comment]
Thank you

**Comment by alejandrojcastaneira** [comment]
Hello everyone, first of all, thanks for a great job in the library! it really saves a lot of time.

Is there a particular reason why the .json support has been removed? Imho, I found it more convenient to work with.

Best regards
