### ISSUE TITLE
Guidance on extracting titles and URLs

### ISSUE THREAD

**Issue by onassar** [attardi/wikiextractor#237]
Hi there -
Thanks for maintaining this library!

I'm opening an issue to ask if anyone here has an example on how to extract just article titles and URLs. That's the only thing I'm looking for, and having trouble grasping how to use the extractor generally. Any examples that can be pointed to?

**Comment by attardi** [comment]
Titles and urls are within the tag <doc> in the first line of each extracted document.
For example:

    <doc id="12" url="https://en.wikipedia.org/wiki?curid=12" title="Anarchism">

**Comment by onassar** [comment]
Grazzi ;-)
Any chance you have some examples on how to actually extra them? I had trouble finding examples on how to actually run it from CLI
