### ISSUE TITLE
Wrong import format on python 3

### ISSUE THREAD

**Issue by vakhokoto** [attardi/wikiextractor#243]
https://github.com/attardi/wikiextractor/blob/6490f5361d7658208ad7f8e5deeb56ee0fe9e02f/wikiextractor/WikiExtractor.py#L66

I have used `wikiextractor` and first when I tried to run the code with `python -m WikiExtractor [args]` I got the error like the one below:

`ImportError: attempted relative import with no known parent package`

When I changed miport format to `from extract import Extractor, ignoreTag, define_template, acceptedNamespaces` there was no error.

**Comment by JuneOrg2020** [comment]
I ran into same error , so I changed import format like yours. but I got new error.

Command
```
python -m wikiextractor.WikiExtractor --json -q -o extracted enwiki-20210120-pages-articles1.xml-p1p41242.bz2
```
Error Message
```
Traceback (most recent call last):
  File "C:\Python38\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python38\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\MyUserName\DEV\wikiextractor\wikiextractor\WikiExtractor.py", line 66, in <module>
    from extract import Extractor, ignoreTag, define_template, acceptedNamespaces
ModuleNotFoundError: No module named 'extract'

```
My Python version is 3.8.2 on Windows 10.

**Comment by JuneOrg2020** [comment]
Probably, you executed command like 
```
python ./wikiextractor/WikiExtractor.py
```
you should execute this instead
```
python -m wikiextractor.WikiExtractor
```

**Comment by attardi** [comment]
Correct, that's the way to do it.
