### ISSUE TITLE
Parser Error

### ISSUE THREAD

**Issue by NoMoreFood** [attardi/wikiextractor#26]
New to Python and WikiMedia so it's possible I'm doing something wrong, but I'm getting error when attempting to translate the Wiktionary dump.  (Note: Reusing the templates file in this example since it takes quite a while to generate.)

C:\Users\administrator\Downloads>WikiExtractor.py --threads 1 --templates TEMPLATES -o MYOUT --html enwiktionary-latest-pages-articles.xml.bz2
INFO: Preprocessing dump to collect template definitions: this may take some time.
INFO: Preprocessed 10000 pages
INFO: Preprocessed 20000 pages
INFO: Starting processing pages from enwiktionary-latest-pages-articles.xml.bz2.
INFO: Using 1 CPUs.
INFO: 16        dictionary
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Windows\Python27\lib\threading.py", line 810, in __bootstrap_inner
    self.run()
  File "C:\Users\administrator\Downloads\WikiExtractor.py", line 2339, in run
    job.extract(self._splitter)
  File "C:\Users\administrator\Downloads\WikiExtractor.py", line 412, in extract
    for line in compact(text):
  File "C:\Users\administrator\Downloads\WikiExtractor.py", line 2035, in compact
    page.append(listItem[n] % line)
KeyError: u' '

**Comment by NoMoreFood** [comment]
It appears sometime like this is enough to set it off:
...
<text>
#*: SomeText
# {{given name|female|from=English}}; SomeText
</text>

**Comment by attardi** [comment]
The program is meant to work with the dump of the Wikipedia articles, not for Wiktionary.

**Comment by NoMoreFood** [comment]
Fair enough.  I thought all of Wikimedia uses the same markup -- reinforced by the fact that program is mentioned on the generic parser list that Wiktionary points to.  If what I posted above would still be valid markup within a Wikipedia article (or you just want to improve error handling), it may be worth investigating. Thanks.

**Comment by attardi** [comment]
Wiktionary uses the same markup, but different naming conventions. For example the titles of templates are capitalized in Wikipedia and not in Wiktionary.
Hence for example the template mechanism currently does not work.

BTW, I tried with the dump you mentioned, but I did not get the error you report.
I got many more pages from the dump also:

INFO: Preprocessed 4260000 pages
INFO: Starting processing pages from enwiktionary-latest-pages-articles.xml.bz2.
INFO: Using 2 CPUs.
INFO: 16        dictionary

Please download the latest version nof WikiExtractor and of Wiktionary and retry.

Don't expect much out of it, for example the entry for 'dictionary' will just be this:

English.
Etymology.
 , from , from , from , perfect past participle of + .

as no template gets expanded.

**Comment by NoMoreFood** [comment]
Ok, I'll try tonight -- I might have been using a filtered page set when i was trying to narrow down what was going wrong.  I should mention that I *was* trying to expand templates and the parser seemed at least run without error after stripping Unicode (might be another issue) and after replacing "^([#*]+){" with "\1 delete_me_later{" to address the aforementioned issue.  More to come.  Thanks for the help.
