### ISSUE TITLE
Warning: Template Errors

### ISSUE THREAD

**Issue by maulidaannisa** [attardi/wikiextractor#288]
Hello, I discovered a difficulty while extracting Wikipedia. I received a warning for template errors while processing the xml file. Do you have any suggestions for how to fix it?

 <img width="873" alt="Screenshot 2022-05-31 at 11 27 33" src="https://user-images.githubusercontent.com/18735318/171142241-ecf419c2-2601-4aa2-af5a-601c646b55ff.png">

Thanks.

**Comment by maulidaannisa** [comment]
It's solved. Thanks

**Comment by mhd0528** [comment]
Hi, may I ask how did you solved this? Thanks

**Comment by guizhenn** [comment]
> It's solved. Thanks

Hi, may I ask how did you solved this? Thanks

**Comment by Vicky-Meng** [comment]
same problem here when parsing the latest cantonese(zh_yue) dump

**Comment by yyxx1997** [comment]
How to solve???
