### ISSUE TITLE
Add option for extracting only template definitions

### ISSUE THREAD

**Issue by cifkao** [attardi/wikiextractor#3]
It would be nice to have an option (e.g. `--no-articles`) to only extract templates and not extract any articles.

It should be possible to achieve this by running `WikiExtractor.py --templates templates.xml dump.xml.bz2` and killing it after it has finished preprocessing the templates. Will it work the way I want?

Thanks!

**Comment by attardi** [comment]
On 4/12/2015 08:42, Ondřej Cífka wrote:
>
> It would be nice to have an option (e.g. |--no-articles|) to only 
> extract templates and not extract any articles.
>
> A possible workaround is to run |WikiExtractor.py --templates 
> templates.xml dump.xml.bz2| and kill it after it has finished 
> preprocessing the templates. Will it work the way I want?
>
Yes, it will work.

--
