### ISSUE TITLE
WARNING: template errors / recursion

### ISSUE THREAD

**Issue by wikihelper** [attardi/wikiextractor#33]
I encountered the problem after running WikiExtractor.py on an italian wiki dump

WikiExtractor.py Version: 2.36 (August 31, 2015)

Error Output:
########################################
INFO: Preprocessed 2300000 pages
INFO: Preprocessed 2400000 pages
INFO: Loaded 126134 templates in 750.0s
INFO: Starting page extraction from res/02/itwiki-latest-pages-articles.xml.xml.
INFO: Using 4 extract processes.
WARNING: template errors 'Archeologia subacquea' (12): untitled(163) recursion(0,0,0)
WARNING: template errors 'Arte' (19): untitled(163) recursion(0,0,0)
WARNING: template errors 'Sport individuale' (83): untitled(163) recursion(0,0,0)
WARNING: template errors 'Astronomo' (268): untitled(337) recursion(0,0,0)
WARNING: template errors 'America Centrale' (279): untitled(163) recursion(0,0,0)
WARNING: template errors 'Antoine de Saint-ExupÃ©ry' (285): untitled(167) recursion(0,0,0)
WARNING: template errors 'Abramo Abulafia' (293): untitled(163) recursion(0,0,0)
WARNING: template errors 'Aeroporto' (286): untitled(330) recursion(0,0,0)
WARNING: template errors 'Alan Kay' (330): untitled(163) recursion(0,0,0)
WARNING: template errors 'Agropoli' (315): untitled(163) recursion(0,0,0)
WARNING: template errors 'Antonio Fogazzaro' (336): untitled(163) recursion(0,0,0)
WARNING: template errors 'Alpi' (337): untitled(163) recursion(0,0,0)
########################################

WikiExtractor.py Version: 2.34 (June 2, 2015)

Error Output:
########################################
WARNING: Max template recursion exceeded!
INFO: 15        Analisi delle frequenze
INFO: 18        Aerofoni
INFO: 19        Arte
WARNING: Max template recursion exceeded!
WARNING: Max template recursion exceeded!
WARNING: Max template recursion exceeded!
WARNING: Max template recursion exceeded!
WARNING: Max template recursion exceeded!
########################################

Link to italian Wiki Dump:
http://download.wikimedia.org/itwiki/latest/itwiki-latest-pages-articles.xml.bz2

**Comment by attardi** [comment]
The warnings are normal, due to malformed templates.
There was an error though in release 2.36 that has been fixed in release 2.37.
