### ISSUE TITLE
Invalid Syntax running ./WikiExtractor.py -h

### ISSUE THREAD

**Issue by nathj07** [attardi/wikiextractor#36]
OS: Centos 6
Python: 2.7.9
Wikiextractor: 2.40 (according to the code, cloned today)

Command: `./WikiExtractor.py -h`
Response:
```
  File "./WikiExtractor.py", line 921
    afterPat = {o: re.compile(openPat + '|' + c, re.DOTALL) for o, c in izip(openDelim, closeDelim)}
                                                              ^
SyntaxError: invalid syntax
```
Any ideas on this one? Are there any pre-requisites I needed to `pip install` first or does this only work with Python 3? Any pointers greatly appreciated.

**Comment by attardi** [comment]
Python 2.7, no prerequisites.

**Comment by nathj07** [comment]
Ok, that's what I have here - Python 2.7. So, any ideas on the syntax issue here?

Thanks for the quick response

**Comment by jmaxx** [comment]
Could you replace the line in question with 
```
afterPat = dict()
for o,c in izip(openDelim, closeDelim):
    afterPat[o] = re.compile(openPat + '|' + c, re.DOTALL)
```

This basically omits the short cut notation of the for loop. Furthermore, do you use any python Environment (e.g. Anaconda)? If that's the case then please try executing the script via `python ./Wikiextractor.py -h` as otherwise it is defaulting to the system's python interpreter in /usr/bin.

**Comment by nathj07** [comment]
Thank you for the quick response. Running it with `python WikiExtractor.py` appears to be working.

As for the code change do you want me to make that and issue a pull req or was that just for me to get up and running? Thanks

**Comment by jmaxx** [comment]
The code change was just to get you beyond that error. As this project requires python 2.7, such syntax ought to be supported (and it would've to be changed in several other places as well, in fact).
I suggest that this solves your problem? For a final check you could call `/usr/bin/python` and see what version caused the syntax error.

**Comment by nathj07** [comment]
```
Python 2.6.6 (r266:84292, Jan 22 2014, 09:42:36) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information
```

Thanks again for the help. I'll get round to cleaning up my environments etc.

**Comment by jmaxx** [comment]
@attardi Beppe, you can close this one.
