### ISSUE TITLE
Typo in readme and help output

### ISSUE THREAD

**Issue by Bubu** [attardi/wikiextractor#38]
You have this in the readme and as output of -h:
```
 -o OUTPUT, --output OUTPUT
                        directory for extracted files (or '-' for dumping to stdin)
```
Should be ```stdout```, I guess?

**Comment by Bubu** [comment]
A few other options in the readme show outdated information:
 - the bytes option default
 - number of default processors

**Comment by attardi** [comment]
Right, thank you.
The number of processes is computed when calling the program: hence the documentation can't tell the exact value.
