### ISSUE TITLE
The script does not work with Python 2.6.6 and there's no required Python version in the docs

### ISSUE THREAD

**Issue by tmnd1991** [attardi/wikiextractor#41]
The script does not work with Python 2.6.6 and there's no required Python version in the docs.
There should be this kind of information somewhere in the doc in order to make the user know the Python version required.
As a side note, the error I get when I try to run it with Python 2.6.6 is:
```
afterPat = {o: re.compile(openPat + '|' + c, re.DOTALL) for o, c in izip(openDelim, closeDelim)}
```

**Comment by attardi** [comment]
Added to the README. Thanks you.
