### ISSUE TITLE
ValueError: I/O operation on closed file

### ISSUE THREAD

**Issue by jrao1** [attardi/wikiextractor#42]
Yes, this is on Windows, but I don't think this is a problem with StringIO.

This error happens because the code opens the file inside the main process of the program by creating the OutputSplitter object, then it passed the object to another process created for reduce_process, and the write to the file occurred in this 2nd process. The problem is sharing file descriptor across processes doesn't work on Windows, I think it would be better if this part is refactored to only open/close the file inside the reduce process.

**Comment by attardi** [comment]
Sounds good.
Can you propose how to refactor the code?

**Comment by jrao1** [comment]
I haven't tried this but my guess is:

* Pass in the parameters needed to open file to reduce_process, let it create the OutputSplitter object (I haven't checked the code closely, I assume reduce_process is the only one using OutputSplitter)
* Then we'll need some way to tell reduce_process that it should close the OutputSplitter object, probably via some kind of IPC?

**Comment by attardi** [comment]
I moved the creation of the OutputSplitter into the reduce_process, which is the only one opening/closing/printing files.
Available in release 2.46.
Please try it on Windows.
