### ISSUE TITLE
Is there a setup.py?

### ISSUE THREAD

**Issue by akupf** [attardi/wikiextractor#43]
Hi, 

A begginers question. Is there a setup.py file? I clone the projects but I can´t see it. 

Thanks

**Comment by attardi** [comment]
No setup required. Just invoke the script as indicated.

**Comment by akupf** [comment]
Thank you!



Enviado con MailTrack
<https://mailtrack.io/install?source=signature&lang=es&referral=ariel.klein@productordigital.com&idSignature=23>

2016-01-18 14:59 GMT+01:00 Giuseppe Attardi <notifications@github.com>:

> No setup required. Just invoke the script as indicated.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/attardi/wikiextractor/issues/43#issuecomment-172533368>
> .
>



-- 
Ariel Klein
Productor Digital
C/Europa 22 2do 3ra
Barcelona 08028
Tel. 93 552 6634
