### ISSUE TITLE
IOError: [Errno 21]

### ISSUE THREAD

**Issue by akupf** [attardi/wikiextractor#44]
Hi again, 

Not sure if this is the right place to ask this. I already extracted the files from the bz2 dump. I´m trying to read the individual files (Gensim`s tutorial): 

class MySentences(object):
     def __init__(self, dirname):
         self.dirname = dirname
 
     def __iter__(self):
         for fname in os.listdir(self.dirname):
             for line in open(os.path.join(self.dirname, fname)):
                 yield line.split()

sentences = MySentences('/home/ariel/extracted') # a memory-friendly iterator
model = gensim.models.Word2Vec(sentences)

And get this error: 

---------------------------------------------------------------------------
IOError                                   Traceback (most recent call last)
<ipython-input-14-2b956f7e1f7e> in <module>()
      9 
     10 sentences = MySentences('/home/ariel/extracted/') # a memory-friendly iterator
---> 11 model = gensim.models.Word2Vec(sentences)

/usr/local/lib/python2.7/dist-packages/gensim-0.12.3-py2.7-linux-x86_64.egg/gensim/models/word2vec.pyc in __init__(self, sentences, size, alpha, window, min_count, max_vocab_size, sample, seed, workers, min_alpha, sg, hs, negative, cbow_mean, hashfxn, iter, null_word, trim_rule, sorted_vocab)
    429             if isinstance(sentences, GeneratorType):
    430                 raise TypeError("You can't pass a generator as the sentences argument. Try an iterator.")
--> 431             self.build_vocab(sentences, trim_rule=trim_rule)
    432             self.train(sentences)
    433 

/usr/local/lib/python2.7/dist-packages/gensim-0.12.3-py2.7-linux-x86_64.egg/gensim/models/word2vec.pyc in build_vocab(self, sentences, keep_raw_vocab, trim_rule)
    493 
    494         """
--> 495         self.scan_vocab(sentences, trim_rule=trim_rule)  # initial survey
    496         self.scale_vocab(keep_raw_vocab=keep_raw_vocab, trim_rule=trim_rule)  # trim by min_count & precalculate downsampling
    497         self.finalize_vocab()  # build tables & arrays

/usr/local/lib/python2.7/dist-packages/gensim-0.12.3-py2.7-linux-x86_64.egg/gensim/models/word2vec.pyc in scan_vocab(self, sentences, progress_per, trim_rule)
    504         min_reduce = 1
    505         vocab = defaultdict(int)
--> 506         for sentence_no, sentence in enumerate(sentences):
    507             if sentence_no % progress_per == 0:
    508                 logger.info("PROGRESS: at sentence #%i, processed %i words, keeping %i word types",

<ipython-input-14-2b956f7e1f7e> in __iter__(self)
      5      def __iter__(self):
      6          for fname in os.listdir(self.dirname):
----> 7              for line in open(os.path.join(self.dirname, fname)):
      8                  yield line.split()
      9 

IOError: [Errno 21] Is a directory: '/home/ariel/extracted/PB'

**Comment by attardi** [comment]
This is an issue about your use of Gensim, not an issue about wikiextractor.
