### ISSUE TITLE
Wikipedia pages with colon in title not extracted

### ISSUE THREAD

**Issue by PascalinDe** [attardi/wikiextractor#47]
We've run into the problem that Wikipedia pages with a colon in the title (e.g. **Star Trek: The Original Series**) are not extracted from a dump. The problem seems to be that the extraction is done on basis of a whitelist (extracted if the part following a colon is an accepted namespace, or the title contains no colon at all). Adding a list of valid namespaces and checking against it (i.e. extracted if following the colon is an accepted namespace, or following the colon is no known namespace or the title contains no colon at all) seems to be a quick fix for the problem, though maybe that leads to other problems?

**Comment by attardi** [comment]
You are right. A better way to check whether a page is a template is to check the element <ns>10</ns>.
I will work on a fix.

**Comment by PascalinDe** [comment]
Great, thank you for your quick reply.

**Comment by attardi** [comment]
The latest version contains the fix. Please try it.

**Comment by PascalinDe** [comment]
I tried it when I closed the issue, it seems to work fine, thank you again.

**Comment by attardi** [comment]
Please try version 2.44, which adds handling of module "If empty", involved in expanding quotations.

**Comment by PascalinDe** [comment]
Seems to work too on our test files. During our tests, we found another issue, for which I will open a separate issue.
