### ISSUE TITLE
Lists are not extracted

### ISSUE THREAD

**Issue by mateuss-ntnu** [attardi/wikiextractor#49]
I have noticed that wikiextractor does not extract lists. I would expect list items to be new line elements, eventually having tabs indicating the level. 

Here is an example of simple english wikipedia article about fish: https://simple.wikipedia.org/wiki/Fish

Extracted text does not contain the list, see example under:

Types of fish.
Fish, the oldest vertebrate group, includes a huge range of types, from the Middle Ordovician, about 490 million years ago, to the present day. These are the main groups:
Certain animals that have the word "fish" in their name are not really fish: Crayfish are crustaceans, and jellyfish are Cnidarians. Some animals look like fish, but are not. Whales and dolphins are mammals, for example.

Between those two paragraphs it should contain a list having multiple levels (see the link above).

My question is if such feature is planned to be implemented?

**Comment by attardi** [comment]
Have you tried option --html, which produces HTML lists?

**Comment by attardi** [comment]
Try the new command line option --lists.

**Comment by mateuss-ntnu** [comment]
It works! Though the multilevel lists are converted to a single level but it is good enough for my usage. Thank you! :+1:
