### ISSUE TITLE
global name 'extract' is not defined

### ISSUE THREAD

**Issue by cifkao** [attardi/wikiextractor#5]
The multithreaded version doesn't work with the `--article` option. [`WikiExtractor.py:1831`](https://github.com/attardi/wikiextractor/blob/8ba0aba2f85b5944b6daf49a69c967f5c85ef7ac/WikiExtractor.py#L1831) causes NameError: global name 'extract' is not defined.

**Comment by zimmeee** [comment]
Does the single-threaded version work with the --article option? If so, how do you invoke it? 
```
python WikiExtractor.py -a /Wikipedia/Train.xml --threads 1
```
Returns the same `extract undefined` error

**Comment by attardi** [comment]
I have a fix for this problem, but I cannot commit at this time, since there are a number of other fixes coming.
The change for this is to replace the call to extract() with:
     Extractor(id, title, [page]).extract()
and then change the method extract to this:
    def extract(self, out=sys.stdout):
        text = ''.join(self.page)
        url = get_url(self.id)
        header = '<doc id="%s" url="%s" title="%s">\n' % (self.id, url, self.title)
        # Separate header from text with a newline.
        header += self.title + '\n\n'
        header = header.encode('utf-8')
        text = clean(text)
        footer = "\n</doc>\n"
        if out != sys.stdout:
            out.reserve(len(header) + len(text) + len(footer))
        out.write(header)
        for line in compact(text):
            out.write(line.encode('utf-8'))
            out.write('\n')
        out.write(footer)

**Comment by attardi** [comment]
Fixed in latest commit.
