### ISSUE TITLE
Extraction of articles cut off

### ISSUE THREAD

**Issue by PascalinDe** [attardi/wikiextractor#50]
Articles get cut off if they are placed in the last or one of the latter positions in the .xml dump. This problem is not present if the output is on the command line, and shows up consistently when outputting to a file. The last version we used in our project was 2.32, which did not produce that error.

**Comment by attardi** [comment]
I made a few fixes to version 2.48.
Check if your problems persist.

**Comment by PascalinDe** [comment]
I tested it with the datasets within which the error occurred, and it works fine now. Thank you again for your help.
