### ISSUE TITLE
Pause when running with "jawiki-20160111-pages-articles-multistream.xml"

### ISSUE THREAD

**Issue by YMMS** [attardi/wikiextractor#52]
Hi Sir,
      I ran your tool "wikiextractor.py" on Ubuntu 14.04 with "jawiki-20160111-pages-articles-multistream.xml". But it paused as some place.
      The last output lines are as below:
`` 779 WARNING: Template errors in article 'ファイル:Hakutaka-485.jpeg' (303793): title(0) recursion(5, 0, 0)``
``780 WARNING: Template errors in article 'ファイル:Maizurukoyuuransen01.jpg' (303877): title(0) recursion(5, 0, 0)``
``781 WARNING: Template errors in article 'ファイル:Chigasakishiyakusyo041111.jpg' (303902): title(0) recursion(5, 0, 0)``

And the process state is as below:
`` PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND``
``22415 yangming  20   0  517612 397328   2012 R  99.7  0.2 134:37.88 python``

**Comment by attardi** [comment]
Looks like the processes have run into a deadlock.
For the moment, try running with a single process, using option:

    --processes 1

**Comment by attardi** [comment]
Please check that you are using the latest version 2.51 or later since for me it is working on that particular dump.

**Comment by YMMS** [comment]
Thank you Sir.
