### ISSUE TITLE
replaceInternalLinks() deletes first and last characters of text in single square brackets

### ISSUE THREAD

**Issue by spyysalo** [attardi/wikiextractor#54]
To replicate:

    from WikiExtractor import replaceInternalLinks
    replaceInternalLinks('ratio of [NADH]')

result:

    'ratio of AD'

expected:

    'ratio of [NADH]'

Single-bracketed strings such as `[NAHD]` are not markup and should be preserved in the text (see e.g. https://en.wikipedia.org/wiki/Adenosine_triphosphate#Regulation_of_biosynthesis, text *ratio of* below formula)

This issue appears to be caused by one of the following invocations of `findBalanced`:

https://github.com/attardi/wikiextractor/blob/master/WikiExtractor.py#L1710
https://github.com/attardi/wikiextractor/blob/master/WikiExtractor.py#L1728

in both cases the problem is that the simple parens around the strings `'[['` and `']]'` do not create tuples with a single value but are rather ignored, i.e.

    findBalanced(text, ('[['), (']]'))

is equivalent to

    findBalanced(text, '[[', ']]')

which is then expanded in `findBalanced` (https://github.com/attardi/wikiextractor/blob/master/WikiExtractor.py#L1040)

    openPat = '|'.join([re.escape(x) for x in openDelim])

into a pattern `\[|\[`that recognizes also a single square bracket. The caller than swallows two characters from the start and end of the match (https://github.com/attardi/wikiextractor/blob/master/WikiExtractor.py#L1718)

    inner = text[s + 2:e - 2]

It should be possible to fix this by adding commas to make the `findBalanced` arguments into single-valued tuples (as likely intended), i.e. replacing
    
    findBalanced(text, ('[['), (']]'))

with

    findBalanced(text, ('[[',), (']]',))

BTW thanks for a great tool!

**Comment by attardi** [comment]
You are absolutely right. It is a quirk of Python syntax for tuples with a single element:
From [http://docs.python.org/tutorial/datastructures.html#tuples-and-sequences](Python docs):

> A special problem is the construction of tuples containing 0 or 1 items: the syntax has some extra quirks to accommodate these. Empty tuples are constructed by an empty pair of parentheses; a tuple with one item is constructed by following a value with a comma (it is not sufficient to enclose a single value in parentheses). Ugly, but effective.

I would however prefer writing:

    ['[[']

than

   ('[[',)
