### ISSUE TITLE
Sections names absent

### ISSUE THREAD

**Issue by gmlvsv** [attardi/wikiextractor#57]
Hi!
Some sections names, e.g. 'Bibliografia' are removed.
For example, for this person
Duino Gorin
 https://it.wikipedia.org/wiki/Duino_Gorin

In XML file I could  see level 2 header:
==Bibliografia==
*''La Raccolta Completa degli Album Panini 1975-1976''
*''La Raccolta Completa degli Album Panini 1960-2004'' - Indici
*''Almanacco illustrato del calcio 1982''. edizione  Pani

But in the processed file just ( no 'Bibliografia' section):

Trascorse in rossonero tre stagioni, fino al 1977, quando passò al Monza.
- "La Raccolta Completa degli Album Panini 1975-1976"
- "La Raccolta Completa degli Album Panini 1960-2004" - Indici
- "Almanacco illustrato del calcio 1982". edizione Panini.

How could I keep sections' names, please?

Thanks!

**Comment by attardi** [comment]
Use option

    --sections

**Comment by gmlvsv** [comment]
~/wikiextractor-master/WikiExtractor.py --sections  -b 500M --lists -o extracted itwiki-latest-pages-articles.xml.bz2
usage: WikiExtractor.py [-h] [-o OUTPUT] [-b n[KMG]] [-c] [--html] [-l]
                        [--lists] [-ns ns1,ns2] [--templates TEMPLATES]
                        [--no-templates] [--escapedoc] [--processes PROCESSES]
                        [-q] [--debug] [-a] [-v]
                        input
WikiExtractor.py: error: unrecognized arguments: --sections

**Comment by attardi** [comment]
Restored the option, in version 2.54.
Thank you.

**Comment by gmlvsv** [comment]
Thank you for quick response!
I re-run it but nothing changes - still missing 'Bibliografia' section:

Duino Gorin
Anche suo fratello minore Fabrizio è stato un calciatore.

Carriera.
Club.
Cresciuto nel Real San Marco di Venezia, esordì con la maglia del Venezia nel campionato di Serie 
Trascorse in rossonero tre stagioni, fino al 1977, quando passò al Monza.
- "La Raccolta Completa degli Album Panini 1975-1976"
- "La Raccolta Completa degli Album Panini 1960-2004" - Indici
- "Almanacco illustrato del calcio 1982". edizione Panini.

**Comment by gmlvsv** [comment]
The problem with such kind of data - 'section + list'
==Bibliografia==
*''La Raccolta Completa degli Album Panini 1975-1976''
*''La Raccolta Completa degli Album Panini 1960-2004'' - Indici
* ''Almanacco illustrato del calcio 1982''. edizione  Panini.

If I put some text before the list it will work:
==Bibliografia==
Bla Bla
-''La Raccolta Completa degli Album Panini 1975-1976''
-''La Raccolta Completa degli Album Panini 1960-2004'' - Indici
- ''Almanacco illustrato del calcio 1982''. edizione  Panini.

**Comment by gmlvsv** [comment]
I added after line 2190:
      if line:  # FIXME: n is '"' 
                    if Extractor.keepLists:
		     if len(headers):
                        if Extractor.keepSections:
                           items = headers.items()
                           items.sort()
                           for i, v in items:
                               page.append(v)
                        headers.clear() 

and now it works for me

**Comment by attardi** [comment]
Thank you for the contribution. I merged it into version 2.55.

**Comment by sooheon** [comment]
@attardi How would I also keep the `== Section ==` formatting around the text?
