### ISSUE TITLE
Wrong dates parse for French Wiki

### ISSUE THREAD

**Issue by gmlvsv** [attardi/wikiextractor#58]
HI!
For Gabriel Biancheri https://fr.wikipedia.org/wiki?curid=9171

**XML dump:**
== Détail des mandats ==

* {{date|21|mars|1977}} - {{date|13|mars|1983}} : adjoint au maire d'[[Hauterives]] ([[Drôme (département)|Drôme]])
* {{date|22|mars|1982}} - {{date|28|décembre|2010}} : conseiller général de la Drôme, élu dans le [[canton du Grand-Serre]]
* {{date|14|mars|1983}} - {{date|28|décembre|2010}} : maire d'Hauterives
* {{date|23|mars|1992}} - {{date|1er|avril|2001}} : conseiller régional de [[Rhône-Alpes]]
* {{date|30|mars|1992}} - {{date|19|septembre|2002}} : vice-président du [[conseil général de la Drôme]]
* {{date|19|juin|2002}} - {{date|28|décembre|2010}} : député de la [[quatrième circonscription de la Drôme]]

**After processing all dates were gone:**
Détail des mandats.
- - : adjoint au maire d'Hauterives (Drôme)
- - : conseiller général de la Drôme, élu dans le canton du Grand-Serre
- - : maire d'Hauterives
- - : conseiller régional de Rhône-Alpes
- - : vice-président du conseil général de la Drôme
- - : député de la quatrième circonscription de la Drôme

**Comment by aadant** [comment]
This is a known issue. You need module support (lua code) to proper support date conversion. 
I think there is a plan to support modules in the future. A first step was to save them (see changelog)
