### ISSUE TITLE
Stopped making progress

### ISSUE THREAD

**Issue by ghost** [attardi/wikiextractor#60]
I am processing the dump of 20160305.

The script ran for about 20 hours and then just stopped making any further progress. I saw two Unix processes but they were both sleeping.

The last few outputs were:

    WARNING: Template errors in article 'Shawn Matthias' (15299966): title(2) recursion(0, 0, 0)
    WARNING: Template errors in article 'Rainey Street Historic District (Austin, Texas)' (15301930): title(0) recursion(116, 0, 0)
    WARNING: Template errors in article 'Alfred Neuland' (15304281): title(2) recursion(0, 0, 0)
    WARNING: Template errors in article 'Humberto Mariles' (15305453): title(2) recursion(0, 0, 0)
    WARNING: Template errors in article 'Rubén Uriza' (15305737): title(2) recursion(0, 0, 0)
    WARNING: Template errors in article 'Santiago Ramírez' (15306967): title(2) recursion(0, 0, 0)

**Comment by attardi** [comment]
This looks like a bug in an earlier version that has been fixed.
Which version are you running?

—

**Comment by geekraver** [comment]
I pulled from github; the copy I pulled has a changelog with most recent entry dated 2016-03-23, and a version 2.42 in setup.py

**Comment by attardi** [comment]
Try running with a single process using option:

   —processes 1

—

**Comment by attardi** [comment]
Which dump are you using?

—

**Comment by geekraver** [comment]
The full English dump. Its about 55GB.

It would be great to have some kind of resume in cases like this so I don't
have to throw away many hours of compute time.

**Comment by geekraver** [comment]
I restarted the job about 36 hours ago and its progressed beyond that point. Not sure what happened.

**Comment by benjaminderei** [comment]
Same problem on latest wikiextractor with latest french dump !

**Comment by benjaminderei** [comment]
Update: I have relaunched the process with only one thread and it seems to continue further.
