### ISSUE TITLE
UnicodeDecodeError and Process Stopped

### ISSUE THREAD

**Issue by mrkiran16** [attardi/wikiextractor#63]
Hi, 

I am trying to extract plaintext from English Wikipedia data dump.

At some point in the extraction process, I get UnicodeDecodeError and the program won't proceed any further. 

![image](https://cloud.githubusercontent.com/assets/15463802/16005242/277d4d62-31a1-11e6-974e-75a2402ee7b7.png)

I tried this:
`line = line.decode('utf-8', 'ignore')`

But the program just exited when it reached the point of error. 

Any way to solve this error or just ignore this in a way that the extraction process is not hampered?

Thank you!

**Comment by attardi** [comment]
Check that your file is complete and not corrupted.
