### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by orangain** [attardi/wikiextractor#65]
Hi,

Is there a plan to support Python 3? Today, Python community is moving from Python 2 to Python 3. For example, in the latest LTS of Ubuntu, 16.04, [Python 3 is the only python installed by default](https://wiki.ubuntu.com/XenialXerus/ReleaseNotes#Python_3).

It would be really nice if the WikiExtractor supports Python 3.

**Comment by attardi** [comment]
I have no experience with Python 3.
Which incompatibilities did you find when running with Python 3?

**Comment by attardi** [comment]
Merged your changes.

**Comment by orangain** [comment]
Thank you for the prompt merge! 😄
