### ISSUE TITLE
How to extract other texts?

### ISSUE THREAD

**Issue by zhihuizheng** [attardi/wikiextractor#70]
How can I extract other texts? such as infobox, category.

**Comment by attardi** [comment]
Currently there is no way: the tool is intended to extract just text.

It shouldn't be hard to do, since those parts are easily identifiable.

--

**Comment by xuefeng-huang** [comment]
hi, @attardi . Is it possible to make it output the category as an attribute like so:
```
<doc id="" revid="" url="" title="" category="">
        ...
        </doc>
```
I had a look of extractor.py and have no idea how I can add that in, can you suggest ways to do that? Thanks in advance.

**Comment by attardi** [comment]
Categories are more than one in general and are listed in a separate section.
If you use --sections, they will show up in the output.

**Comment by dvirginz** [comment]
When I add --sections, I don't see the categories
