### ISSUE TITLE
ERROR:root:Processing page: 972 服部あゆみ 

### ISSUE THREAD

**Issue by ablodge** [attardi/wikiextractor#73]
When I run WikiExtractor.py on the Japanese Wikipedia dump jawiki-latest-pages-articles.xml, I get this line in stdout repeated for each page:
"ERROR:root:Processing page: 972 服部あゆみ "
After going through the entire input, the program finishes but the output is an empty text file.
Any ideas? If you can help I very much appreciate it.

(Using version 2.40, the latest version gives these same errors plus NameError on 'escape_doc')

**Comment by dsalychev** [comment]
Hi @ablodge.

At the moment I've no idea what actually went wrong, however I'd like to suggest you running the script again with ```--no-templates```, ```--escapedoc``` and ```--debug``` arguments and put an output which you'll receive here.

**Comment by ablodge** [comment]
Running the latest version, the output looks like this. It looks the same if I run it with or without the arguments` --no-templates`, ` --escapedoc` and `--debug`.

> ERROR:root:Processing page: 453 プロジェクト:プロジェクト関連文書
> Traceback (most recent call last):
>   File "C:\Users\austin\Desktop\WikiExtractor.py", line 2641, in extract_process
>     e.extract(out)
>   File "C:\Users\austin\Desktop\WikiExtractor.py", line 511, in extract
>     text = compact(self.clean())
>   File "C:\Users\austin\Desktop\WikiExtractor.py", line 628, in clean
>     if escape_doc:
> NameError: global name 'escape_doc' is not defined
> ERROR:root:Processing page: 448 山梨県
> Traceback (most recent call last):
>   File "C:\Users\austin\Desktop\WikiExtractor.py", line 2641, in extract_process
>     e.extract(out)
>   File "C:\Users\austin\Desktop\WikiExtractor.py", line 511, in extract
>     text = compact(self.clean())
>   File "C:\Users\austin\Desktop\WikiExtractor.py", line 628, in clean
>     if escape_doc:
> NameError: global name 'escape_doc' is not defined
> 


Thanks for the help!

**Comment by dsalychev** [comment]
It looks like this output is a bit informative at least :)

**Comment by attardi** [comment]
This is an error from an older release. Download the latest.
