### ISSUE TITLE
No Articles get Extracted

### ISSUE THREAD

**Issue by Mustyy** [attardi/wikiextractor#74]
python WikiExtractor.py -cb 250K -o extracted enwiki-20160801-pages-articles-multistream.xml.bz2
INFO: Loaded 0 templates in 0.0s
INFO: Starting page extraction from enwiki-20160801-pages-articles-multistream.xml.bz2.
INFO: Using 31 extract processes.
INFO: Finished 31-process extraction of 0 articles in 0.1s (0.0 art/s)

What am I doing wrong? Cant seem to figure this out

**Comment by attardi** [comment]
Check your files: did you download the dump correctly?
