### ISSUE TITLE
EOFError: compressed file ended before the logical end-of-stream was detected

### ISSUE THREAD

**Issue by Mustyy** [attardi/wikiextractor#75]
This error seems to happen after reaching 
INFO: Extracted 340000 articles (615.7 art/s)

Any ideas why the process is being interrupted?

**Comment by attardi** [comment]
Are you running out of memory?

**Comment by Mustyy** [comment]
No I have plenty of memory 
I downloaded another wiki dump 
This time I'm getting an error regarding the multiprocessor script 
Something to do with pipes and threads perhaps. 
Any ideas? 

Best Regards,
Mustafa

**Comment by attardi** [comment]
Which OS you are using? Which version of Python? Which dump are you using?

**Comment by Mustyy** [comment]
Hey
Thanks for getting back to me
I figured out that the data dump was corrupted but now it's working well

Next step would be once the word2vec training is done. Perhaps to connect it to Spacy to do entity name recognition and pos. 

Any suggestions on how you'd proceed?
The ultimate goal being to feed a custom corpus into this trained model and for it to do everything I'm trying to do with the wiki dump plus the Spacy NER


Mustafa

**Comment by attardi** [comment]
You need a training set for NER. If you have one, you can use the NER in:

https://github.com/attardi/deepnl

that uses WE as features.

**Comment by showhero** [comment]
我也遇到了同样的错误，在多进程中解压N多文件，提示这个问题，但并不是每个文件都提示这个错误，内存也够用。不知道怎么解决，我重新运行程序希望能不会出现该问题，但问题的原因没有找到
