### ISSUE TITLE
global name 'extract' is not defined

### ISSUE THREAD

**Issue by yuritupizin** [attardi/wikiextractor#76]
Hi,
I have downloaded the following file : enwiki-latest-pages-articles.xml
and ran the following command :
WikiExtractor.py -o "output path" "xml path" in cmd
and I keep getting the following error for each article : global name 'extract' is not defined.
Please assist.
Thanks,
Yuri

**Comment by attardi** [comment]
You must supply the input file as explained here:
https://github.com/attardi/wikiextractor/wiki#Usage

**Comment by attardi** [comment]
On which OS you are running?

**Comment by Nitzg** [comment]
i have the same problem.
i'm using windows 8.1, 64 bits and python 2.7
with the 2.58 version of the code, i also tried an older one but keep getting errs(the example is from an attempt with the hebrew dump, but i've also tried the english one).

ERROR:root:Processing page: 328 ירדן
Traceback (most recent call last):
  File "WikiExtractor.py",
 line 2641, in extract_process
    e.extract(out)
  File "WikiExtractor.py",
 line 511, in extract
    text = compact(self.clean())
  File "CWikiExtractor.py",
 line 628, in clean
    if escape_doc:
NameError: global name 'escape_doc' is not defined

**Comment by yuritupizin** [comment]
Hi,
thanks for the quick replay, I'm using windows 7 64bits, python 2.7 .

**Comment by attardi** [comment]
Those errors do not occur on linux.
It might be a problem with windows misunderstanding linux newlines (\n, rather than \c\n).
Try converting the script file to dos format.

**Comment by yuritupizin** [comment]
tried to find & replace all "\n" with "\c\n" as you suggested but nothing changed. 
same error keeps jumping for each article.
any other ideas?
thanks,

**Comment by attardi** [comment]
Try add this line in front of main:

escape_doc = False

**Comment by attardi** [comment]
I have committed the change to version 2.59. Try it, please.
