### ISSUE TITLE
I can't find any example

### ISSUE THREAD

**Issue by cryptid11** [attardi/wikiextractor#78]
Is there anything somewhere?

**Comment by attardi** [comment]
You can find information on usage on the wiki pages.

**Comment by cryptid11** [comment]
I can't see them here https://github.com/attardi/wikiextractor/wiki I actually need to extract articles in English about Italian cities is there a way to do that?

**Comment by attardi** [comment]
The tool extracts the text from all articles in a dump, it does not provide a select interface.
The only usage is the one explained here:
https://github.com/attardi/wikiextractor/wiki#Usage

**Comment by cryptid11** [comment]
Anyway this is not what I'm looking for. Thanks.
