### ISSUE TITLE
quote lines inside {{}} is removed 

### ISSUE THREAD

**Issue by rajasankar** [attardi/wikiextractor#80]
example

for this para in  https://en.wikipedia.org/wiki/Anarchism

> 
> They included {{quote|[[Louise Michel]], the Reclus brothers, and [[Eugene Varlin]] (the latter murdered in the repression afterwards). As for the reforms initiated by the Commune, such as the re-opening of workplaces as co-operatives, anarchists can see their ideas of associated labour beginning to be realised&amp;nbsp;... Moreover, the Commune's ideas on federation obviously reflected the influence of [[Pierre-Joseph Proudhon|Proudhon]] on French radical ideas. Indeed, the Commune's vision of a communal France based on a federation of delegates bound by imperative mandates issued by their electors and subject to recall at any moment echoes Bakunin's and Proudhon's ideas (Proudhon, like Bakunin, had argued in favour of the &quot;implementation of the binding mandate&quot; in 1848&amp;nbsp;... and for federation of communes). Thus both economically and politically the Paris Commune was heavily influenced by anarchist ideas.&lt;ref&gt;{{cite web|url=http://flag.blackened.net/revolt/anarchism/writers/anarcho/commune.html|title=The Paris Commune|work=blackened.net}}&lt;/ref&gt;}} George Woodcock states:
> {{quote|a notable contribution to the activities of the Commune and particularly to the organisation of public services was made by members of various anarchist factions, including the mutualists Courbet, Longuet, and Vermorel, the [[Collectivist anarchism|libertarian collectivists]] Varlin, Malon, and Lefrangais, and the bakuninists Elie and [[Elisée Reclus]] and Louise Michel.&lt;ref name=&quot;Anarchism 1962&quot;/&gt;}}

the output is 

> They included George Woodcock states:

removing `text = dropNested(text, r'{{', r'}}')` calling the `text = replaceExternalLinks(text)` with {{ }} does the trick. 

There might be error in wiki data itself but just want to file this issue incase this is reproduced.

**Comment by attardi** [comment]
It seems you have disabled template expansion or are using an older version.
Actually the current version drops instead "George Woodcock states:".
I will investigate this.

**Comment by rajasankar** [comment]
Yes I have disabled template expansion because it is not needed for that work I'm doing. 

I checked the wiki, it seems that markup changed in the article. May be a human error in the wiki too because I havent checked that for other pages. 

I will post the updates once I run more tests with this. Thanks for the nice too.

**Comment by bejean** [comment]
What is not working for me is that 

"Les sites Internet d'information du {{w|Gouvernement fédéral des États-Unis|gouvernement américain}} {{VOA News}} ont été victimes d'une attaque informatique"

produces 

"Les sites Internet d'information du ont été victimes d'une attaque informatique"

Everything between {{ and }} is dropped.

"{{w|Gouvernement fédéral des États-Unis|gouvernement américain}}" should produce "Gouvernement fédéral des États-Unis"

The commande line I am using is :

./WikiExtractor.py -q  -o /tmp /tmp/frwikinews-20160901-pages-articles.xml.bz2

Regards

**Comment by attardi** [comment]
In Wikimedia markup the  {{ }} represent templates, which are to be expanded.
If there is no template with that name, the expansion is empty.
In your case it looks like there is no definition for template w nor for template VOA_News.

—
