### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by christofs** [attardi/wikiextractor#84]
Hi there, great tool! It appears there is an error or lack of detail in the documentation here: http://medialab.di.unipi.it/wiki/Wikipedia_Extractor . Or maybe this is OS-specific (I'm on Ubuntu 16.04 LTS) or depends on the language version of the wiki (although it really shouldn't). 
I have used the line similar to the one shown there, on the command line: 
```
WikiExtractor.py -cb 250K -o extracted itwiki-latest-pages-articles.xml.bz2
```
If I do this, I get the following error message:
```
WikiExtractor.py: command not found
```
I then did this, adding "python" at the beginning, but still using the "*.xml.bz2" file as input file (just with the frwiki dump):
```
python WikiExtractor.py frwiki-latest-pages-articles.xml.bz2
```

With this, I get the following error message:
```
INFO: Loaded 0 templates in 0.0s
INFO: Starting page extraction from frwiki-20160920-pages-articles-multistream.xml.bz2.
INFO: Using 3 extract processes.
INFO: Finished 3-process extraction of 0 articles in 0.0s (0.0 art/s)

```
A folder "text" is created but then nothing happens. 
If I try to use python 3, I get another error message: 
```
Traceback (most recent call last):
  File "WikiExtractor.py", line 60, in <module>
    from cStringIO import StringIO
ImportError: No module named 'cStringIO'
```
However, then I used python 2.7, first extracted the "bz2" archive (using bzip2) and then used the "*.xml" file as input, like this: 
```
python WikiExtractor.py frwiki-latest-pages-articles.xml
```
With this, all works just fine.
It may be worth telling people this. It drove me mad for a while because I could not figure out what I was doing wrong. Partly, this may just be because I was calling this thing from the command line. But the extraction bit should not depend on this.

Thanks!

**Comment by attardi** [comment]
Thanks for the appreciation.

As far as invoking the command, you need to have the command in your path to call it.
If you don't, you must add it, for example:

    ./WikiExtractor.py ...

As for the second error, you said you called it with:

    WikiExtractor.py frwiki-latest-pages-articles.xml.bz2


but the output says you are using a different file:

    INFO: Starting page extraction from frwiki-20160920-pages-articles-multistream.xml.bz2

so please check that you are using the correct input file.

**Comment by christofs** [comment]
Thanks. My examples were indeed imprecise. But my point is that it appears necessary to extract the bz2 archive ("frwiki-20160920-pages-articles-multistream.xml.bz2", in my case) before calling WikiExtractor on the extracted file ("frwiki-20160920-pages-articles-multistream.xml", in my case). This step is not mentioned in the documentation.

**Comment by attardi** [comment]
No, the script does uncompress by itself.

**Comment by BastianAM** [comment]
Hi there! Can you please help to figure out why keep getting this problem:
`WikiExtractor.py --json eswiki-latest-abstract.xml
INFO: Loaded 0 templates in 0.0s
INFO: Starting page extraction from eswiki-latest-abstract.xml.
INFO: Using 3 extract processes.
INFO: Finished 3-process extraction of 0 articles in 0.1s (0.0 art/s)`

What am I doing wrong / missing?

Thanks!

**Comment by shreyu2403** [comment]
hello,
the command after this step is not working for me.
find extracted -name '*bz2' -exec bzip2 -c {} \; > text.xml
it runs through all the files and says .b2z already exists.
how do I extract the plain text out of all the spilted files?

**Comment by Embedding** [comment]
> hello,
> the command after this step is not working for me.
> find extracted -name '*bz2' -exec bzip2 -c {} ; > text.xml
> it runs through all the files and says .b2z already exists.
> how do I extract the plain text out of all the spilted files?

I have the same problem. Did you solve the problem?
