### ISSUE TITLE
How to merge extracted files?

### ISSUE THREAD

**Issue by caceter** [attardi/wikiextractor#95]
Hello, 
I am a true beginner. I managed to extract my corpus into folder with 
`python WikiExtractor.py trwiki-20161201-pages-articles.xml.bz2 -b 500K -o extracted`
It looks like files have no extension, trying to convert them to text but there are too many files. How can I merge the files with the scripts features? Files look like wiki_00,wiki_01,wiki_02...

Thanks

**Comment by attardi** [comment]
The files are in what I call <doc> format, which is just the plain text of each article, included in a <doc> tag that contains the id of the article.
