### ISSUE TITLE
Some special characters

### ISSUE THREAD

**Issue by sandra1993** [attardi/wikiextractor#96]
1. not remove xml escape characters,such as '&', then when parse xml , there will arise SAXParseException as following. 
SAXParseException: test.xml:5:438: not well-formed (invalid token)

2. There are some tags that doesn't matched.
`describes his student as being happy by having
<poem>at his beddes heed
Twenty bookes, clad in blak or reed,
Of aristotle and his philosophie,</poem>
The Italian poet Dante says of Aristotle in the first circles of hell,
<poem>vidi 'l maestro di color che sanno
seder tra filosofica famiglia.
Tutti lo miran, tutti onor li fanno:
quivi vid'ïo Socrate e Platone
che 'nnanzi a li altri più presso li stanno;</poem>
<poem>I saw the Master there of those who know,
Amid the philosophic family,
By all admired, and by all reverenced;
...
</doc>
`

The last  "poem"  tag doesn't have matched tag  that will also arise SAXParseException .

**Comment by attardi** [comment]
Are you processing the output with an XML parser?
The output is not in XML, it is plain text with tags just to separate documents.

**Comment by bstriner** [comment]
Parsing the default output seems to require a custom parser because it is neither plain text nor XML. The JSON output is easy to handle. Here is a gist for a small class that reads the JSON extracts into python objects for anyone having similar issues.

https://gist.github.com/bstriner/7062dbefd54bd66955a4aa67f8f0cdc4

```python
path = "Y:\\wikipedia\\json"
model = WikiModel(path)
for doc in model.docs():
  print doc.title
  print doc.text
```

Cheers

**Comment by attardi** [comment]
Thanks for the contribution.
