### ISSUE TITLE
There is some stuff in curly brackets that looks auxilliary, but it's not

### ISSUE THREAD

**Issue by searchivarius** [attardi/wikiextractor#98]
Hi, thanks again for the nice extractor. 

One issue that I noticed though (and don't know how to fix) is that certain stuff in curly brackets that looks like infobox or some other auxilliary code, but it's not. For example the following code:
``{{convert|93|m|ft|abbr=off|sp=us}}``
is deleted when you parse the page https://en.wikipedia.org/wiki/Ayodhya
However, it should produce the text **93 meters (305 feet).**
I wonder if it is possible to fix (it may not be easy though).
Just for the sake of accuracy I used the dump ``enwiki-20161020-pages-articles.xml.bz`` and the master branch (without changes in my recent pull request). However, it will likely be reproducible with the latest dump as well.

Thank you!

**Comment by attardi** [comment]
The double curly braces represent templates. They are like macros that must be expanded. WikiExtractor tries to do that, but some macros are defined as Lua scripting code, which is not currently supported, hence the templates is ignored.

**Comment by searchivarius** [comment]
Ok, if this is hard to fix, it's not worth it.
